### PR TITLE
feat: update libnice to version 0.1.13

### PR DESCRIPTION
**Pull request by Akagi201**
update libnice to version 0.1.13

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Closing as we've deprecated Homebrew/boneyard but thanks for the PR anyway!

**Comment by Akagi201** [comment]
@MikeMcQuaid So, where should I commit the formulae?

**Comment by MikeMcQuaid** [comment]
Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

**Comment by MikeMcQuaid** [comment]
Or submit it to homebrew/core if it builds again on Sierra, is getting updates and is useful to you.

**Pull request closed without merging**
