### PR TITLE
gptfdisk: import from core

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by bfontaine** [comment]
Could you please explain in the commit message why you’re boneyarding it?

**Comment by dunn** [comment]
Oh! yeah, good point.

**Comment by DomT4** [comment]
Darn, you're going to cause a merge conflict on my `icu4c` PR :stuck_out_tongue_winking_eye:

**Comment by bfontaine** [comment]
Thank you @dunn! :smiley:

**Comment by dunn** [comment]
Such is the cutthroat world of Homebrew maintaining.

**Pull request closed without merging**
