### PR TITLE
tinyscheme: migrate from core

### PR DESCRIPTION
**Pull request by woodruffw**
Reference: Homebrew/homebrew-core#999

### CODE REVIEW

**Comment by woodruffw** [comment]
@ilovezfs Any update on this?

**Comment by ilovezfs** [comment]
Did you happen to file an upstream issue about the segfault? It's particularly peculiar not only in that it was seemingly not reproducible locally, but also in that it didn't occur with gcc. If for no other reason than intellectual curiosity, it would be nice to

**Comment by woodruffw** [comment]
I sent the maintainers an email, but the project seems to be in hibernation or disuse. I'll follow up.

**Comment by ilovezfs** [comment]
So one (new) issue with this PR: the bottle block should be removed, which is something we're now trying to do consistently upon boneyarding: https://github.com/Homebrew/homebrew-boneyard/commits/master

**Comment by woodruffw** [comment]
Sounds good, removed it.

**Comment by ilovezfs** [comment]
:+1:

**Pull request closed without merging**
