### PR TITLE
urweb: migrate back to core

### PR DESCRIPTION
**Pull request by eranmeir**
Part of https://github.com/Homebrew/homebrew-core/pull/2182

### CODE REVIEW

**Comment by UniqMartin** [comment]
Merged in 9f30ff5cf93281e601e4a1207a308c41d7ec0a62. Thank you for this contribution to Homebrew, @eranmeir! :tada:

**Comment by ilovezfs** [comment]
@UniqMartin this makes me think it would be nice to have a generic migrate X to Y.

**Comment by UniqMartin** [comment]
@ilovezfs You mean a generalization of the `boneyard-formula-pr` command as `migrate-formula-pr`? Or going one step further a `read-my-mind-and-just-do-it-pr` command? 😀

**Comment by ilovezfs** [comment]
The former, but if you have a proposal for the latter that doesn't involve inserting wires into the skull, I'm curious.

**Pull request merged**
