### PR TITLE
Use sha256 where possible

### PR DESCRIPTION
**Pull request by ilovezfs**
and remove formulae with sha1 if a working URL couldn't be found

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> comment out sha1 where a working URL couldn't be found

I'd just delete the formulae (and remove from `tap_migrations.json`) in those cases; they are still in Git history but if they cannot be downloaded there's little use keeping them around.

**Comment by MikeMcQuaid** [comment]
Otherwise 👍

**Comment by ilovezfs** [comment]
@MikeMcQuaid PR refreshed.

**Comment by ilovezfs** [comment]
:ship:'d

**Comment by MikeMcQuaid** [comment]
Thanks!

> and remove from tap_migrations.json

Just to be explicit: were there any in this for homebrew/core?

**Comment by ilovezfs** [comment]
@MikeMcQuaid https://github.com/Homebrew/homebrew-core/pull/3501.

**Pull request closed without merging**
