### PR TITLE
Move frink to boneyard

### PR DESCRIPTION
**Pull request by enilsen16**
Clean up, format, and move frink to the boneyard.

### CODE REVIEW

**Comment by DomT4** [comment]
Where did `frink` come from?

**Comment by enilsen16** [comment]
I tried to `brew install

**Comment by enilsen16** [comment]
Thoughts @DomT4?

**Comment by UniqMartin** [comment]
I don't think there's any benefit to boneyarding this now, given how long ago it has been removed and how comparatively simple the formula is. If the situation ever changes, it will be easier to create the formula anew instead of reusing what might be in this tap.

**Comment by DomT4** [comment]
Agree with @UniqMartin there's little point retroactively boneyarding. It's something we should do with pretty much everything going forwards, but I don't think we need to crawl backwards to rectify the old system either.

**Comment by enilsen16** [comment]
Fair enough. Would it be better to put this formula in the head-only tap?
Either way I'll go ahead and close this. Thanks!

**Comment by DomT4** [comment]
`head-only` is in the process of being deprecated, because `head-only` is pretty lousy UX and nobody has really wanted to work on improving that. If you want to support it I'd probably suggest doing so in a tap of your own to be honest.

**Pull request closed without merging**
