### PR TITLE
Deprecate Homebrew/boneyard.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This tap was deprecated because Homebrew 1.1.12 provides the commands necessary to show old versions of formulae and because this tap required maintenance overhead and had poor usability.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:skull: of :skull:

**Comment by halfnibble** [comment]
Can someone please describe what those new brew commands are because I am genuinely interested in using them.

**Comment by MikeMcQuaid** [comment]
@halfnibble Basically just `brew install`, `brew info`, `brew search` now handle deleted formulae. In your case you probably want `brew log` or just `git log`.

**Comment by danielkza** [comment]
I can't seem to install a previously deleted formula (apt-cacher-ng) now that boneyard is gone. Am I missing something?

```bash
$ brew install apt-cacher-ng
Error: No available formula with the name "apt-cacher-ng" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
$ brew search apt-cache
No formula found for "apt-cache".
Closed pull requests:
apt-cacher-ng: migrate to boneyard (https://github.com/Homebrew/homebrew-core/pull/3886)
$ brew --version
Homebrew 1.2.1
Homebrew/homebrew-core (git revision b39c; last commit 2017-05-18)
```

**Comment by MikeMcQuaid** [comment]
@danielkza We intentionally don't support installation of deleted formulae. You will need to recreate the formula yourself.

**Pull request merged**
