### PR TITLE
Move coremod, dbslayer, pathfinder, tcpurify to boneyard.

### PR DESCRIPTION
**Pull request by geoff-codes**
Corresponds to https://github.com/Homebrew/homebrew/pull/37014.

### CODE REVIEW

**Comment by mistydemeo** [comment]
I believe coremod was renamed to libxmp-lite, but still exists: http://sourceforge.net/projects/xmp/files/libxmp/4.3.5/

**Comment by geoff-codes** [comment]
@mistydemeo Got it. Fixed in the main PR.

**Comment by mistydemeo** [comment]
Thank you!

**Comment by mikemcquaid** [comment]
Related Homebrew/homebrew PRs: https://github.com/Homebrew/homebrew/pull/37063 https://github.com/Homebrew/homebrew/pull/37056 https://github.com/Homebrew/homebrew/pull/37066 https://github.com/Homebrew/homebrew/pull/37069

**Pull request closed without merging**
