### PR TITLE
llvm32: rename cloog dependency

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I'm not sure it's necessary to fix things up in the boneyard FYI but if you'd rather 👍

**Comment by ilovezfs** [comment]
It is if you have the boneyard tapped and don't want to see warnings spammed into the console every time you run, for example, `brew uses anything`

**Comment by ilovezfs** [comment]
Note this is the same reason we've had to fix https and sha256 in the boneyard.

**Comment by MikeMcQuaid** [comment]
Ok, cool.

**Pull request merged**
