### PR TITLE
libqglviewer: migrate from core

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Goes together with https://github.com/Homebrew/homebrew-core/pull/6827.

Created with `brew boneyard-formula-pr` because Qt4 is EOL, GPL library.

### CODE REVIEW

**Comment by ikoruk** [comment]
This library compiles perfectly well with qt5 replacing `depends_on "qt"` with `depends_on "qt5"`. Is boneyard the best place to put it? Or should these formulas be updated with qt5?

**Comment by MikeMcQuaid** [comment]
@ikoruk In this case it's partly that it doesn't compile and partly that it's a GPL library meaning if you use this in your application your application must be open-sourced.

**Comment by Moisan** [comment]
`homebrew-sicence/g2o` and `homebrew-sicence/dgtal` have optional dependencies on this formula. This is also related to [homebrew-science qt5 transition](https://github.com/Homebrew/homebrew-science/issues/4595). 

Is GPL really a deal breaker? I see a quick mention of GPL in the [Acceptable-Formula guidelines](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) but not a clear definition of which license are acceptable or not.

**Comment by MikeMcQuaid** [comment]
> homebrew-sicence/g2o and homebrew-sicence/dgtal have optional dependencies on this formula.

It may make sense to add it to homebrew/science.

> Is GPL really a deal breaker?

The GPL? Definitely not. The GPL for a library which has no homebrew/core dependencies? People are very unlikely to be aware when they `brew install libqglviewer` that if they use that library in their application they now legally need to open-source their entire application.

**Pull request merged**
