### PR TITLE
Complete core formula bottling

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
By boneyarding these unbottled formulae. See https://github.com/Homebrew/homebrew-core/pull/2194

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Whoops, didn't mean to squash these 😞

**Comment by ilovezfs** [comment]
You could get out the force push light saber. :zap:

**Comment by MikeMcQuaid** [comment]
@ilovezfs an inelegant weapon for a less civilised age 😉

**Comment by ilovezfs** [comment]
Well, this *is* the boneyard after all. Bam bam, bam bam bam.

**Pull request merged**
