### PR TITLE
Use ENV.deparallelize.

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes #271.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I think stuff like this creates more work for ourselves than is necessary. I appreciate the PR but it's annoying that we even get incoming PRs about this stuff. I think it may be worth considering not doing migrations to the boneyard at all, let people get formulae out of Git history instead and no longer do `tap_migrations` to this tap and instead ensure that people with the formula currently installed don't get a 💥 (most of which I think should have been addressed by https://github.com/Homebrew/brew/pull/1812). Thoughts?

**Comment by ilovezfs** [comment]
I think as long as this tap exists, and as long as it throws deprecation exceptions/errors/warnings/whatever in the same way other taps do, then it needs to be updated just like everything else when a deprecation occurs. That to me is distinct from "maintaining the formulae" in terms of making sure they build or function properly, or get updated to their latest versions, etc.

If the tap ceases to exist, or if brew is modified to suppress deprecation exceptions/errors/warnings/whatever when they "originate" in the boneyard, then there would be no need for a PR like this.

I think one risk in eliminating the tap is that we'll end up inadvertently re-admitting things to core that were removed for very good reason just because no one remembers that they were previously in core, or whoever does remember doesn't notice the incoming PRs.

**Comment by MikeMcQuaid** [comment]
> I think one risk in eliminating the tap is that we'll end up inadvertently re-admitting things to core that were removed for very good reason just because no one remembers that they were previously in core, or whoever does remember doesn't notice the incoming PRs.

I think we could make `brew audit --new-formula` check for whether a formula with the same name was ever previously in Homebrew and fail so it requires manual intervention. Thoughts? 

We're also seeing issues like https://github.com/Homebrew/brew/issues/1654 that result from other taps adopting formulae from the boneyard.

**Comment by ilovezfs** [comment]
>I think we could make brew audit --new-formula check for whether a formula with the same name was ever previously in Homebrew and fail so it requires manual intervention. Thoughts?

Right. The tap is implicitly doing that for us right now, but it could be handled with code. Even a basic blacklist would serve the same function.

>let people get formulae out of Git history

That will raise the technical bar, unless there's some tooling to assist. It's arguably a "feature" to raise the bar, but it may be unfair when our reason for dropping the formula is particular to Homebrew ideology, not a security issue (e.g., "everything must build with clang or else" is not an especially good reason to play keep away with the old formula file if it still builds and works with the relevant gcc).

**Comment by MikeMcQuaid** [comment]
> Right. The tap is implicitly doing that for us right now, but it could be handled with code. Even a basic blacklist would serve the same function.

👍 

> That will raise the technical bar, unless there's some tooling to assist. It's arguably a "feature" to raise the bar, but it may be unfair when our reason for dropping the formula is particular to Homebrew ideology, not a security issue (e.g., "everything must build with clang or else" is not an especially good reason to play keep away with the old formula file if it still builds and works with the relevant gcc).

Yes, that's fair. `brew log` could probably be trivially extended to do this nicely.

**Comment by ilovezfs** [comment]
Another approach here might be to have an expiration for things in the boneyard. So like 90 days, and then poof, deleted, rather than eliminating the tap altogether.

**Pull request merged**
