### PR TITLE
webkitgtk: migrate from core

### PR DESCRIPTION
**Pull request by DomT4**
Goes together with https://github.com/Homebrew/homebrew-core/pull/11243.

Created with `brew boneyard-formula-pr` because repeatedly breaks/causes issues & consequently sits there stuck on versions with publicly-known CVEs frequently.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Did you check if `devhelp` can build without it?

**Comment by DomT4** [comment]
It doesn't.

**Comment by DomT4** [comment]
```
checking for DEVHELP... no
configure: error: Package requirements (
  gthread-2.0 >= 2.10.0
  gtk+-3.0 >= 3.19.3
  webkit2gtk-4.0 >= 2.6.0
  gio-2.0 >= 2.37.3
) were not met:

No package 'webkit2gtk-4.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEVHELP_CFLAGS
and DEVHELP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by ilovezfs** [comment]
pity.

:fire:

**Comment by DomT4** [comment]
Aye, slightly annoying. On the upside, `gnome-builder` loses a really heavy by-default dependency. Small silver lining.

**Comment by MikeMcQuaid** [comment]
Would like @tschoonj's opinion here.

**Comment by DomT4** [comment]
On the `webkitgtk` issue he's commented before at least. Not sure how Tom feels about `devhelp`.

https://github.com/Homebrew/homebrew-core/pull/9053#issuecomment-279220087

**Comment by tschoonj** [comment]
I am ok with boneyarding both webkitgtk and devhelp. I am currently working on a patch for gnome-builder in Homebrew/homebrew-core#11224, which will remove the devhelp dependency.

**Comment by DomT4** [comment]
I've handled `gnome-builder` in https://github.com/Homebrew/homebrew-core/pull/11243 already to get the PR to pass. Could wait a few more days if not I guess and then rebase against master once your PR is complete & merged.

**Pull request merged**
